services:
  - type: web
    name: prou-backend
    rootDirectory: backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false

staticSites:
  - name: prou-frontend
    rootDirectory: frontend
    buildCommand: npm install --silent 2>/dev/null || echo "No package.json found, skipping npm install"
    publishPath: ./